# Plugins 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

# C-a Prefix Setting
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Truecolor Terminal Color
set-option -sa terminal-overrides ",xterm*:Tc"

# Neovim tmux integration
set-option -sg escape-time 10
set focus-events on

# Config Gruvbox
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' # or 'light'

# Key-bindings
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
# Copy-mode shortcut
bind-key v copy-mode
# 30% v-split
bind-key E split-window -h -l 32% -c "#{pane_current_path}"

bind-key A split-window -h -b -c "#{pane_current_path}"
bind-key a split-window -h -c "#{pane_current_path}"
# Common configuration
set -g base-index 1	
set -g pane-base-index 1
set -g automatic-rename on
set -g renumber-windows on
set -g status-justify left
set -g mouse on
set -g mode-keys vi

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
